name: Test
on:
  push:
    branches:
       - master

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - {name: Linux, python: '3.8', os: ubuntu-latest, tox: py38}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
           python-version: ${{ matrix.python }}

      - name: Setup up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Get Markupsafe cache
        uses: actions/cache@v2
        id: markupsafe-cache
        with:
          path: markupsafe-cache/
          key: markupsafe-cache

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build markupsafe for aarch64
        #if: matrix.os == 'ubuntu-latest' && steps.markupsafe-cache.outputs.cache-hit != 'true'
        run: |
          ./test.sh
          wget https://files.pythonhosted.org/packages/ac/7e/1b4c2e05809a4414ebce0892fe1e32c14ace86ca7d50c70f00979ca9b3a3/MarkupSafe-1.1.0.tar.gz
          tar -xvzf MarkupSafe-1.1.0.tar.gz
          cd MarkupSafe-1.1.0
          python -m cibuildwheel --output-dir ../markupsafe-cache
        env:
          CIBW_BUILD: "cp37-*"
          CIBW_ARCHS: aarch64

      - name: Build wheel
        run: |
          ls markupsafe-cache/
          python -m cibuildwheel --output-dir dist
        env:
          CIBUILDWHEEL_BUILD_VERBOSITY: 3
          CIBW_BUILD: "cp37-*"
          CIBW_BEFORE_BUILD: ls markupsafe-cache/ ;pip install --find-links=markupsafe-cache/ markupsafe==1.1.0
          CIBW_ARCHS_LINUX: aarch64
